package com.example.embeddedsystemscareerguide.models

import com.example.embeddedsystemscareerguide.services.UserProgressSyncService.UserProgress

/**
 * A milestone badge, computed purely from cloud progress data - no separate
 * Firestore collection or write path is needed since every condition below is
 * already loaded whenever [UserProgress] is loaded.
 *
 * Replaces HomeFragment's achievements section, which previously called
 * setupAchievements() to unconditionally hide the RecyclerView and show the
 * "no achievements yet" empty state regardless of actual progress -
 * permanently, for every user, no matter what they'd done.
 */
data class Achievement(
    val id: String,
    val emoji: String,
    val title: String,
    val description: String,
    val isEarned: (UserProgress) -> Boolean
)

object Achievements {

    /**
     * Ordered roughly by how early a user is expected to reach each one.
     *
     * Built per-call because the learning path is generated by the model and
     * has no fixed length - the milestones that depend on how much of the path
     * is finished close over [totalStages] instead of assuming a count. Pass 0
     * when the real total is not known yet; path-relative badges then stay
     * unearned rather than unlocking against a made-up denominator.
     */
    fun allFor(totalStages: Int): List<Achievement> = listOf(
        Achievement(
            id = "first_stage",
            emoji = "🎯",
            title = "First Steps",
            description = "Complete your first stage",
            isEarned = { it.completedStages.isNotEmpty() }
        ),
        Achievement(
            id = "streak_7",
            emoji = "🔥",
            title = "Week Warrior",
            description = "Reach a 7-day streak",
            isEarned = { it.bestStreak >= 7 }
        ),
        Achievement(
            id = "xp_500",
            emoji = "⭐",
            title = "Getting Started",
            description = "Earn 500 total XP",
            isEarned = { it.totalXP >= 500 }
        ),
        Achievement(
            id = "stages_half",
            emoji = "🏆",
            title = "Halfway There",
            description = "Complete half of your learning path",
            isEarned = { totalStages > 0 && it.completedStages.size * 2 >= totalStages }
        ),
        Achievement(
            id = "streak_14",
            emoji = "🚀",
            title = "Momentum",
            description = "Reach a 14-day streak",
            isEarned = { it.bestStreak >= 14 }
        ),
        Achievement(
            id = "perfect_stage",
            emoji = "✨",
            title = "Perfectionist",
            description = "Earn 3 stars on a stage",
            isEarned = { progress -> progress.stageStars.values.any { it >= 3 } }
        ),
        Achievement(
            id = "xp_2500",
            emoji = "💎",
            title = "XP Master",
            description = "Earn 2,500 total XP",
            isEarned = { it.totalXP >= 2500 }
        ),
        Achievement(
            id = "streak_30",
            emoji = "👑",
            title = "Dedicated",
            description = "Reach a 30-day streak",
            isEarned = { it.bestStreak >= 30 }
        ),
        Achievement(
            id = "all_stages",
            emoji = "🎓",
            title = "Graduate",
            description = "Complete every stage in your path",
            isEarned = { totalStages > 0 && it.completedStages.size >= totalStages }
        )
    )

    fun earned(progress: UserProgress, totalStages: Int): List<Achievement> =
        allFor(totalStages).filter { it.isEarned(progress) }
}
